authapp/urls.py
from django.urls import path

from authapp.views import login, logout, register, PasswordChangeRedirectView, api_users, APIBbUsersDel, \
    APIRubricViewSet

from authapp.views import APIBbUsers

app_name = "authapp"

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('change_password/', PasswordChangeRedirectView.as_view(), name='change_password'),  # lesson_39_hw

    # path('api/v1/users/', api_users),  # lesson_49_hw
    path('api/v1/users/', APIBbUsers.as_view()),  # lesson_52_hw
    # path('api/v1/users/', APIRubricViewSet.as_view()),  # lesson_52_hw

    path('api/v1/users/<str:username>/', APIBbUsersDel.as_view()),  # lesson_52_hw
]

bboard/urls.py
from django.urls import path, re_path, include
from django.views.decorators.cache import cache_page
from django.views.generic.dates import WeekArchiveView
from rest_framework.routers import DefaultRouter

from bboard.models import Bb
from bboard.views import BbAddView, BbByRubricView, BbDetailView, BbIndexView, BbMonthArchiveView, \
    BbRedirectView, BbIndexRedirectView, index, by_rubric, BbLoginRedirectView, BbByRubricByDateView, \
    IceCreamCreateView, rubrics, bbs, search, CaptchaLibraryView, BbEditView, api_rubrics, api_rubric_detail, \
    APIRubrics, APIRubricDetail, APIRubricViewSet

vals = {
    'name': 'index',
    'beaver': 'бобёр'
}

# urlpatterns = [
#     re_path(r'^$', index, name='index'),
#     re_path(r'^(?P<rubric_id>[0-9]*)/$', by_rubric, vals, name='by_rubric'),
#     re_path(r'^add/$', BbCreateView.as_view(), name='add'),
#     path('login/', login, name='login'),
# ]

router = DefaultRouter()
router.register('rubrics', APIRubricViewSet)

urlpatterns = [
    path('', index, name='index'),
    path('rubrics/', rubrics, name='rubrics'),

    # path('api/v1/rubrics/', api_rubrics),
    # path('api/v1/rubrics/<int:pk>/', api_rubric_detail),

    # lesson_50 Start
    # path('api/v1/rubrics/', APIRubrics.as_view()),
    # path('api/v1/rubrics/<int:pk>/', APIRubricDetail.as_view()),

    path('api/v1/', include(router.urls)),
    # lesson_50 End

    path('bbs/<int:rubric_id>/', bbs, name='bbs'),
    path('page/<int:page>/', index, name='page'),

    # path('', BbIndexView.as_view(), name='index'),
    path('index/', BbIndexRedirectView.as_view(), name='index_old'),
    path('<int:rubric_id>/', by_rubric, vals, name='by_rubric'),
    # path('<int:rubric_id>/', BbByRubricView.as_view(), name='by_rubric'),
    # path('<int:rubric_id>/page/<int:page>/', BbByRubricView.as_view(), name='rubric_page'),
    path('<int:rubric_id>/page/<int:page>/', BbByRubricByDateView.as_view(), name='rubric_page'),  # lesson_20_hw
    # path('add/', BbCreateView.as_view(), name='add'),
    path('add/', BbAddView.as_view(), name='add'),
    # path('add/save/', add_save, name='add_save'),
    # path('add/', add, name='add'),
    # path('add/', add_and_save, name='add'),
    path('update/<int:pk>/', BbEditView.as_view(), name='update'),

    path('read/<int:rec_id>/', BbDetailView.as_view(), name='read'),

    path('<int:year>/<int:month>/', BbMonthArchiveView.as_view()),
    path('<int:year>/week/<int:week>/', WeekArchiveView.as_view(
        model=Bb,
        date_field='published',
        context_object_name='bbs',
        template_name='bboard/bb_archive_month.html'
    )),
    path('detail/<int:pk>/', BbDetailView.as_view(), name='detail'),
    path('detail/<int:year>/<int:month>/<int:day>/<int:pk>/', BbRedirectView.as_view(), name='old_detail'),

    path('add_icecream/', IceCreamCreateView.as_view(), name='add_icecream'),  # lesson_25_hw

    path('search/', search, name='search'),

    path('captcha_library/', CaptchaLibraryView.as_view(), name='captcha_library'),  # lesson_32_hw
]

firstsite/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bboard.urls')),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('testapp/', include('testapp.urls', namespace='testapp'), name='testapp'),

    path('accounts/login/', LoginView.as_view(next_page='index'), name='login'),
    # path('accounts/login/?next=index', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('accounts/password_change/', PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),
    path('accounts/password_change/done/', PasswordChangeDoneView.as_view(
        template_name='registration/password_changed.html'),
        name='password_change_done'),
]

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    # import debug_toolbar

    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/inc_main_menu.html
{% load count_bbs %}
{% load bootstrap4 %}

<nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark" data-bs-theme="dark">

    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item d-block">
                    <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Главная</a>
                </li>

                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'authapp:logout' %}">
                            Logout: {{ user.username }}
                        </a>
                    </li>
                {% else %}
                {#        <a href="{% url 'authapp:login' %}">#}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'authapp:login' %}">
                            Login
                        </a>
                    </li>

                    <div class="toast fade show" role="alert" aria-live="assertive" aria-atomic="true">
                        <div class="toast-header">
                            <strong class="me-auto">Blaz</strong>
                            <small>Бот</small>
                            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Закрыть"></button>
                        </div>
                        <div class="toast-body">
                            Вы не вошли! Вход: <a class="nav-link" href="{% url 'authapp:login' %}">Login</a>
                        </div>
                    </div>
                {% endif %}

                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'authapp:change_password' %}">
                            Изменить пароль
                        </a>
                    </li>
                {% endif %}

                {% if user.is_authenticated %}
                    {% if user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'rubrics' %}">
                                Изменить рубрики
                            </a>
                        </li>
                    {% endif %}
                {% endif %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'add' %}">
                        Добавить
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'add_icecream' %}">  {# lesson_25_hw #}
                        Добавить мороженое
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'captcha_library' %}">  {# lesson_32_hw #}
                        Библиотека каптч
                    </a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Рубрики
                    </a>
                    <ul class="dropdown-menu">
                        {% for rubric in rubrics %}
                                <li><a class="dropdown-item" href="{{ rubric.get_absolute_url }}">
                                    {{ rubric.name }}{% if count_bb %}
                                        ({{ count_bb|count_bbs:rubric.pk }})
                                    {% endif %}
                                </a></li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>